### PR TITLE
Added PHPUnit 8 support

### PR DESCRIPTION
**Pull request by webimpress**

### CODE REVIEW

**Comment by OndraM** [comment]
I guess `:void` must be added as return type to tearDown() etc. methods. This is backward compatible change (won't break support for PHPUnit 7 etc.), so it could be IMHO safely done.

**Comment by webimpress** [comment]
@OndraM Yes, but the changes we need to do in https://github.com/php-mock/php-mock, and there we still support PHP 5.6. I can prepare compatibility level to support both versions, but not sure if it is worth to do that.

**Comment by OndraM** [comment]
Well I don't think its worth the effort: you can just drop the support of old PHP - who uses it can still use the old version of this library, it won't stop working for him. But for anyone with PHPUnit 6+ must already use PHP 7+ (see https://phpunit.de/supported-versions.html ).

**Comment by KartaviK** [comment]
I agree with @OndraM . I think would be better release major version with dropped php5. In readme should point which version should use.

PS
In any case i created fork for my self :D

**Comment by webimpress** [comment]
I've decided to add PHPUnit 8 support without new major release.
I can't see the point of creating new major release without any additional features/changes, as adding the support of v8 was quite easy.

@KartaviK @OndraM Please have a look on PR: https://github.com/php-mock/php-mock/pull/22 if you have a sec. Thanks!

**Pull request merged**
